//Default constants
var WS_SETTINGS_VAR_STRINGS = ["WS_DROP_AVAILABLE", "WS_DROP_AVAILABLE", "WS_DROP_RECEIVED"];
var WS_DROP_AVAILABLE = "drop_available";
var WS_DROP_READ_RECEIPT = "drop_read_receipt";
var WS_DROP_RECEIVED = "drop_received";
var WS_SHOULD_DROP_AVAILABLE = true;
var WS_SHOULD_DROP_READ_RECEIPT = false;
var WS_SHOULD_DROP_RECEIVED = false;


var WS_DROP_OPTIONS = {};
WS_DROP_OPTIONS[WS_DROP_AVAILABLE] = WS_SHOULD_DROP_AVAILABLE;
WS_DROP_OPTIONS[WS_DROP_READ_RECEIPT] = WS_SHOULD_DROP_READ_RECEIPT;
WS_DROP_OPTIONS[WS_DROP_RECEIVED] = WS_SHOULD_DROP_RECEIVED;